<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;
use CodeIgniter\I18n\Time;

class ItemSeeder extends Seeder
{
    public function run()
    {
        $faker = \Faker\Factory::create('id_ID');

        $items = [
            [
                'nama' => 'Pohon 1',
                'scene' => 1,
                'harga' => 10000,
                'repaired' => 0,
                'width' => 99,
                'height' => 105,
                'z-index' => 2,
            ],
            [
                'nama' => 'Pohon 1',
                'scene' => 1,
                'harga' => 10,
                'repaired' => 1,
                'shop_image' => 'assets/climate/pohon-kuning-shop.png',
                'width' => 99,
                'height' => 105,
                'z-index' => 2,
            ],
            [
                'nama' => 'Pohon 2',
                'scene' => 1,
                'harga' => 10000,
                'repaired' => 0,
                'width' => 99,
                'height' => 100,
                'z-index' => 2,
            ],
            [
                'nama' => 'Pohon 2',
                'scene' => 1,
                'harga' => 10,
                'repaired' => 1,
                'shop_image' => 'assets/climate/pohon-merah-shop.png',
                'width' => 99,
                'height' => 100,
                'z-index' => 2,
            ],
            [
                'nama' => 'Background',
                'scene' => 1,
                'harga' => 10000,
                'repaired' => 0,
                'width' => 99,
                'height' => 100,
                'z-index' => -2,
            ],
            [
                'nama' => 'Background',
                'scene' => 1,
                'harga' => 10000,
                'repaired' => 1,
                'width' => 99,
                'height' => 100,
                'z-index' => -2,
            ],
            [
                'nama' => 'Tanah',
                'scene' => 1,
                'harga' => 10000,
                'repaired' => 0,
                'width' => 99,
                'height' => 100,
                'z-index' => -2,
            ],
            [
                'nama' => 'Tanah',
                'scene' => 1,
                'harga' => 10000,
                'repaired' => 1,
                'width' => 99,
                'height' => 100,
                'z-index' => -2,
            ],
            [
                'nama' => 'Sungai',
                'scene' => 1,
                'harga' => 10000,
                'repaired' => 0,
                'width' => 85,
                'height' => 115,
                'z-index' => 2,
            ],
            [
                'nama' => 'Sungai',
                'scene' => 1,
                'harga' => 20,
                'repaired' => 1,
                'shop_image' => 'assets/climate/sungai-shop.png',
                'width' => 85,
                'height' => 115,
                'z-index' => 2,
            ],
            [
                'nama' => 'Bukit',
                'scene' => 1,
                'harga' => 15,
                'repaired' => 1,
                'shop_image' => 'assets/climate/bukit-shop.png',
                'width' => 99,
                'height' => 100,
                'z-index' => 0,
            ],
            [
                'nama' => 'Rumput',
                'scene' => 1,
                'harga' => 5,
                'repaired' => 1,
                'shop_image' => 'assets/climate/rumput-shop.png',
                'width' => 99,
                'height' => 100,
                'z-index' => 3,
            ],
            [
                'nama' => 'Buah',
                'scene' => 1,
                'harga' => 5,
                'repaired' => 1,
                'shop_image' => 'assets/climate/buah-shop.png',
                'width' => 99,
                'height' => 100,
                'z-index' => 3,
            ],
            [
                'nama' => 'Bunga',
                'scene' => 1,
                'harga' => 5,
                'repaired' => 1,
                'shop_image' => 'assets/climate/bunga-shop.png',
                'width' => 99,
                'height' => 100,
                'z-index' => 3,
            ],
            [
                'nama' => 'Kupu-kupu',
                'scene' => 1,
                'harga' => 15,
                'repaired' => 1,
                'shop_image' => 'assets/climate/kupu-shop.png',
                'width' => 99,
                'height' => 100,
                'z-index' => 3,
            ],
            [
                'nama' => 'Jerapah',
                'scene' => 1,
                'harga' => 15,
                'repaired' => 1,
                'shop_image' => 'assets/climate/jerapah-shop.png',
                'width' => 99,
                'height' => 100,
                'z-index' => 3,
            ],
            [
                'nama' => 'Gedung Merah',
                'scene' => 2,
                'harga' => 5,
                'repaired' => 1,
                'shop_image' => 'assets/eco/red-shop.png',
                'width' => 100,
                'height' => 100,
                'z-index' => 7,
            ],
            [
                'nama' => 'Gedung Orange',
                'scene' => 2,
                'harga' => 8,
                'repaired' => 1,
                'shop_image' => 'assets/eco/orange-shop.png',
                'width' => 100,
                'height' => 100,
                'z-index' => 7,
            ],
            [
                'nama' => 'Gedung Kuning',
                'scene' => 2,
                'harga' => 10,
                'repaired' => 1,
                'shop_image' => 'assets/eco/yellow-shop.png',
                'width' => 100,
                'height' => 100,
                'z-index' => 5,
            ],
            [
                'nama' => 'Gedung Hijau',
                'scene' => 2,
                'harga' => 12,
                'repaired' => 1,
                'shop_image' => 'assets/eco/green-shop.png',
                'width' => 100,
                'height' => 100,
                'z-index' => 6,
            ],
            [
                'nama' => 'Gedung Biru',
                'scene' => 2,
                'harga' => 15,
                'repaired' => 1,
                'shop_image' => 'assets/eco/blue-shop.png',
                'width' => 100,
                'height' => 100,
                'z-index' => 3,
            ],
            [
                'nama' => 'Gedung Ungu',
                'scene' => 2,
                'harga' => 20,
                'repaired' => 1,
                'shop_image' => 'assets/eco/purple-shop.png',
                'width' => 100,
                'height' => 100,
                'z-index' => 2,
            ],
            [
                'nama' => 'Bianglala',
                'scene' => 2,
                'harga' => 7,
                'repaired' => 1,
                'shop_image' => 'assets/eco/bianglala-shop.png',
                'width' => 100,
                'height' => 100,
                'z-index' => 4,
            ],
            [
                'nama' => 'Mobil Mewah',
                'scene' => 2,
                'harga' => 15,
                'repaired' => 1,
                'shop_image' => 'assets/eco/car-shop.png',
                'width' => 100,
                'height' => 100,
                'z-index' => 11,
            ],
            [
                'nama' => 'Background',
                'scene' => 2,
                'harga' => 10000,
                'repaired' => 0,
                'width' => 100,
                'height' => 100,
                'z-index' => 11,
            ],
            [
                'nama' => 'Sky',
                'scene' => 2,
                'harga' => 10000,
                'repaired' => 0,
                'width' => 100,
                'height' => 100,
                'z-index' => 11,
            ],
            [
                'nama' => 'Road',
                'scene' => 2,
                'harga' => 10000,
                'repaired' => 0,
                'width' => 100,
                'height' => 100,
                'z-index' => 11,
            ],
        ];

        foreach ($items as $item) {
            $item['created_at'] = Time::now();
            $item['updated_at'] = Time::now();
            $this->db->table('item')->insert($item);
        }
    }
}
